### ISSUE TITLE
Debian buster and PostgreSQL12 unable to install

### ISSUE THREAD

**Issue by marcoarthur** [vpikulik/postgres_osm_pbf_fdw#15]
I Installed the requirements (package names changed from deb 9)
<pre>
apt install postgresql-server-dev-all libjson-c-dev libjson-c3 libprotobuf-dev protobuf-compiler libprotobuf-c1 zlib1g-dev zlib1g
</pre>
 
and tried to install in debian buster (pg12) using pgnx tool and the got this error:

<pre>
root@Database:/var/lib/postgresql# pgxn install osm_fdw
INFO: best version: osm_fdw 4.0.0
INFO: saving /tmp/tmpDU76MG/osm_fdw-4.0.0.zip
INFO: unpacking: /tmp/tmpDU76MG/osm_fdw-4.0.0.zip
INFO: building extension
make -C src/osm_reader fileformat.pb-c.c
make[1]: Entering directory '/tmp/tmpDU76MG/osm_fdw-4.0.0/src/osm_reader'
protoc-c --c_out=/tmp/tmpDU76MG/osm_fdw-4.0.0/src/osm_reader fileformat.proto
make[1]: protoc-c: Command not found
Makefile:5: recipe for target 'fileformat.pb-c.c' failed
make[1]: *** [fileformat.pb-c.c] Error 127
make[1]: Leaving directory '/tmp/tmpDU76MG/osm_fdw-4.0.0/src/osm_reader'
Makefile:50: recipe for target 'src/osm_reader/fileformat.pb-c.c' failed
make: *** [src/osm_reader/fileformat.pb-c.c] Error 2
ERROR: command returned 2: make PG_CONFIG=/usr/bin/pg_config all
</pre>

It seems the tool named  *protoc-c*, changed *protoc* , I create an alias (symlink) , but got this error:
<pre>
root@Database:/var/lib/postgresql# pgxn install osm_fdw                                                                                                                    
INFO: best version: osm_fdw 4.0.0                      
INFO: saving /tmp/tmpwVSNfz/osm_fdw-4.0.0.zip                            
INFO: unpacking: /tmp/tmpwVSNfz/osm_fdw-4.0.0.zip                                                                                                                        
INFO: building extension                                                                                                                                                   
make -C src/osm_reader fileformat.pb-c.c                                                                                                                                   
make[1]: Entering directory '/tmp/tmpwVSNfz/osm_fdw-4.0.0/src/osm_reader'                                                                                                  
protoc-c --c_out=/tmp/tmpwVSNfz/osm_fdw-4.0.0/src/osm_reader fileformat.proto
[libprotobuf WARNING google/protobuf/compiler/parser.cc:547] No syntax specified for the proto file: fileformat.proto. Please use 'syntax = "proto2";' or 'syntax = "proto3";' t
o specify a syntax version. (Defaulted to proto2 syntax.)                                                                                                                
protoc-gen-c: program not found or is not executable                                                                                                                       
--c_out: protoc-gen-c: Plugin failed with status code 1.                                                                                                                 
Makefile:5: recipe for target 'fileformat.pb-c.c' failed                                                                                                                 
make[1]: *** [fileformat.pb-c.c] Error 1                                              
make[1]: Leaving directory '/tmp/tmpwVSNfz/osm_fdw-4.0.0/src/osm_reader'                     
Makefile:50: recipe for target 'src/osm_reader/fileformat.pb-c.c' failed                                                                                                 
make: *** [src/osm_reader/fileformat.pb-c.c] Error 2
</pre>

I guess it is not yet compatible to pg12, but I would like to help in port if you plan to do it.

**Comment by vpikulik** [comment]
Hello. Sorry for the outdated README.
Please have a look and try to install required packages as in [.ci.yml](https://github.com/vpikulik/postgres_osm_pbf_fdw/blob/master/.ci.yml#L53).
From you message, I see that `protoc-gen-c` is not installed. It is provided by `protobuf-c-compiler` package in Debian Buster.

**Comment by marcoarthur** [comment]
Thanks the reply, I was able to install after read the instructions from the yaml file.
