### ISSUE TITLE
Build errors against v14

### ISSUE THREAD

**Issue by devrimgunduz** [vpikulik/postgres_osm_pbf_fdw#17]
Hi,

v14 beta1 is out, and osm_fdw fails to build against v14. Logs are attached. Can you please take a look?

[osm_fdw_pg14.txt](https://github.com/vpikulik/postgres_osm_pbf_fdw/files/6591139/osm_fdw_pg14.txt)

Thanks!

Regards, Devrim

**Comment by devrimgunduz** [comment]
ping!

**Comment by vpikulik** [comment]
https://github.com/vpikulik/postgres_osm_pbf_fdw/pull/18
Done

**Comment by devrimgunduz** [comment]
Hi,

Thanks. Can you please release a new version? We need tarballs to build packags.

Regards, Devrim
