### ISSUE TITLE
Postgres 9.6?

### ISSUE THREAD

**Issue by tsykes** [vpikulik/postgres_osm_pbf_fdw#6]
Hi. Thanks for this extension. Is it or planned to be compatible with Postgres 9.6?

**Comment by vpikulik** [comment]
Hi. Yes, I want. But at first I should to support pg 9.5. I will try to do this during the next some weeks. Then I will think about 9.6

**Comment by vpikulik** [comment]
Hi. v2.0.1 works with 9.6.
